// Autogenerated during build phase.
// Any changes you make to this file will be overwritten.
declare namespace LyricsLessNamespace {
  export interface ILyricsLess {
    lyricWrapper: string
    truncate: string
  }
}

declare const LyricsLessModule: LyricsLessNamespace.ILyricsLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: LyricsLessNamespace.ILyricsLess
}

export = LyricsLessModule
