// Autogenerated during build phase.
// Any changes you make to this file will be overwritten.
declare namespace HomeLessNamespace {
  export interface IHomeLess {
    App: string
    colMedia: string
    hero: string
  }
}

declare const HomeLessModule: HomeLessNamespace.IHomeLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: HomeLessNamespace.IHomeLess
}

export = HomeLessModule
