// Autogenerated during build phase.
// Any changes you make to this file will be overwritten.
declare namespace SearchLessNamespace {
  export interface ISearchLess {
    errorMessage: string
  }
}

declare const SearchLessModule: SearchLessNamespace.ISearchLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: SearchLessNamespace.ISearchLess
}

export = SearchLessModule
